== ロボットの交代/Robot Substitution

=== 交代エリア/Substitution Areas

[[goal-substitution-area]]
==== ゴール側交代エリア/Goal Substitution Area (Division A only)
ロボットが自陣側ゴールラインから少なくとも 0.3m フィールド外に出ているとき、ロボットはゴール側交代エリア内にあるとみなされる。 +
A robot is considered to be in the Goal Substitution Area if it is at least 0.3 meters outside the field, behind its own goal line.

ロボットは試合中、ゴール側交代エリアにいてよい。
これらは自由に移動することができ、以下のルールに従う必要がある: +
Robots are allowed to remain in the Goal Substitution Area while the game is running.
They are allowed to move freely and must comply with the following rules:

* <<停止/Stop, 「停止」>>中、もしくは<<フリーキック/Free Kick, フリーキック>>中におけるボールとの最小距離制約を満たすこと +
Minimum ball distance during <<停止/Stop, stop>> or <<フリーキック/Free Kick, free kick>>
* <<ボール配置/Ball Placement, ボール配置>>に干渉しないこと +
Must not interfere with <<ボール配置/Ball Placement, ball placement>>

[[center-substitution-area]]
==== センター交代エリア/Center Substitution Area
ロボットが少なくとも部分的にフィールドのマージン内にあり、かつ<<ハーフウェーライン/Halfway Line, ハーフウェーライン>>から最大1mの距離にあれば、ロボットはセンター交代エリア内にあるとみなされる。 +
A robot is considered to be in the Center Substitution Area if it is at least partially inside the field margin and at a distance of at most 1 meter from the <<ハーフウェーライン/Halfway Line, halfway line>>.

=== ルール/Rules
.定義/Definition
ロボットはそれぞれのチームの<<ハンドラー/Robot Handler, ハンドラー>>によって交代される。他のいかなるチームメンバーもロボットを出し入れすることは許可されない。 +
Robots are substituted by the <<ハンドラー/Robot Handler, robot handler>> of the respective team. No other team member is allowed to take robots out or put robots in.

<<ハンドラー/Robot Handler, ハンドラー>>は、visionシステムに干渉しない色の長袖を着用することが推奨される。 +
The <<ハンドラー/Robot Handler, robot handler>> should prefer to use long sleeves and colors that won't interfere with the vision system.

以下のすべての条件に適合する場合は、ゲーム中のいつでも<<主審/Referee, 主審>>に確認を取ることなくロボットを投入もしくは除去することができる: +
Robots can always be taken in and out during game play without notifying the <<主審/Referee, referee>> if all the following conditions are met:

. ロボットが各チームの交代エリアにある。 +
The robot is in its team's substitution area.
. ボールはロボットから少なくとも0.5m離れた地点にある。 +
The ball must be at least 0.5 meters away from the robot.

加えて、要求があればロボットはどの位置からでも以下の手順に従い除去させられる: +
Additionally, robots can be taken out from any position on request using the procedure below:

. 任意の時点で<<ハンドラー/Robot Handler, ハンドラー>>がロボットの交代を要求する。 +
The <<ハンドラー/Robot Handler, robot handler>> requests robot substitution at any time.
. <<Game Controller, Game Controller>>が次の機会に<<Halt>>により試合を停止させる。 +
The <<Game Controller, game controller>> will <<Halt, halt>> the game at the next opportunity.
. <<ハンドラー/Robot Handler, ハンドラー>>は試合が<<Halt>>により停止している間、必要に応じてフィールドに入りロボットに触れる。 +
The <<ハンドラー/Robot Handler, robot handler>> may enter the field and touch robots now.
. <<ハンドラー/Robot Handler, ハンドラー>>はロボットを外に出す +
The <<ハンドラー/Robot Handler, robot handler>> takes robots out.
. <<ハンドラー/Robot Handler, ハンドラー>>は交代が完了したら<<主審/Referee, 主審>>に連絡する +
The <<ハンドラー/Robot Handler, robot handler>> informs the <<主審/Referee, referee>> when done.
. 両チームともロボットの交代が終わったら、<<主審/Referee, 主審>>は<<Game Controller Operator, game controller operator>>に連絡する。 +
When both teams finished the robot substitution, the <<主審/Referee, referee>> informs the <<Game Controller Operator, game controller operator>>.
. <<Game Controller Operator, game controller operator>>は<<停止/Stop, 「ストップ」>>コマンドを実行し、その後試合を続行する。 +
The <<Game Controller Operator, game controller operator>> performs a <<停止/Stop, stop>> followed by continuing the game.

ロボットを配置するいかなる時点でも、フィールド上にある各チームのロボットの台数は指定された最大数を越えてはならない。 +
The maximum allowed number of robots of the team on the field must not be exceeded at any time when putting robots in.

.用途/Usage
いかなる理由であってもロボットの交代ができる。
一度の交代につき、チームは20秒間だけロボットを退場させることができる。この時間を超えた場合、新たにロボット交代の時間が開始される。
各チームはハーフタイムごとに5回まで罰則なくロボットの交代を行うことができる。　
これ以降のロボット交代は交代ごとに <<ロボット交代回数超過/Excessive Robot Substitutions, ロボット交代回数超過>>の反則となる。 +
Robots can be substituted for any reason.
A substitution grants the team 20 seconds to take robots out. After that time, a new substitution is started.
Each team has 5 free substitutions per halftime.
Every additional substitution will result in an <<ロボット交代回数超過/Excessive Robot Substitutions, excessive robot substitutions foul>> for the team.

ロボットの交代の意思表示は次のようにして行う： +
A robot substitution intent can be made by:

. <<ハンドラー/Robot Handler, ハンドラー>>は<<Game Controller Operator, game controller operator>>に通知することで<<Game Controller, game controller>>に意図を入力する。 +
A <<ハンドラー/Robot Handler, robot handler>> by informing the <<Game Controller Operator, game controller operator>> who in turn enters the intent into the <<Game Controller, game controller>>.
. <<ハンドラー/Robot Handler, ハンドラー>>は、提供されていれば<<リモコン/Remote Control, リモコン>>を使用する。 +
A <<ハンドラー/Robot Handler, robot handler>> by using the <<リモコン/Remote Control, remote control>>, if provided.
. チームのソフトウェアは<<Game Controller, game controller>>へリクエストを送信する。 +
A team software by sending a request to the <<Game Controller, game controller>>.
. <<Game Controller, game controller>>は当該チームに許された最大ロボット数を超えていないかを確認し(例えばチームが<<イエローカード/Yellow Card, イエロー>>か<<レッドカード/Red Card, レッドカード>>を受け取ったあと等)、リクエストを処理する。 +
The <<Game Controller, game controller>> itself if a team exceeds the maximum number of robots (for example after a team receives a <<イエローカード/Yellow Card, yellow>> or <<レッドカード/Red Card, red card>>).

片方のチームの交代の意図のために試合がHaltされた場合、少なくとも一台のロボットが除去されなければならない。交代のために試合がHaltされていない場合に限り交代の意図を取り消すことができる。 +
If the game was halted due to a substitution intent by a team, at least one robot must be taken out by this team. A substitution intent can be revoked unless the game was not already halted for substitution.

ボール配置後、試合が継続する直前にどちらかのチームがロボットを交代する意思がある場合、<<Game Controller, game controller>>は自動的に試合を<<Halt>>する。 +
If a robot substitution intent for either team is present just before the game would continue after ball placement, the <<Game Controller, game controller>> automatically <<Halt, halts>> the game.
